import bcrypt from 'bcrypt';
import crypto from 'crypto';
import {pool,q} from './db.js';
import {problem,normalizeDni,normalizePhone} from './core.js';
import {queueUserNotification} from './notifications.js';

export const LEGAL_VERSIONS={terms:'2026-09-20-v1',risks:'2026-09-20-v1',conduct:'2026-09-20-v1',privacy:'2026-09-20-v3',whatsapp:'2026-09-20-v1'};
export function publicUser(u){return {id:u.id,first_name:u.first_name,last_name:u.last_name,gender:u.gender,role:u.role,verification_status:u.verification_status,current_category_number:u.current_category_number,discipline_state:u.discipline_state,identity_resubmit_reason:u.identity_resubmit_reason||null,identity_resubmit_requested_at:u.identity_resubmit_requested_at||null};}
export async function register(reqBody,{ip=null,userAgent=null,identityDocuments=null}={}){const {firstName,lastName,dni,phone,password,gender,legalAcceptances}=reqBody||{};const clean=normalizeDni(dni),ph=normalizePhone(phone);if(!firstName||!lastName||!ph||!password||!['male','female'].includes(gender))throw problem('Datos incompletos');if(clean.length<7||clean.length>9)throw problem('DNI inválido');if(String(password).length<8)throw problem('La contraseña debe tener al menos 8 caracteres');for(const [type,version] of Object.entries(LEGAL_VERSIONS)){if(legalAcceptances?.[type]!==version)throw problem(`Debés aceptar ${type}`);}const front=identityDocuments?.front,back=identityDocuments?.back;if(!front?.buffer||!back?.buffer)throw problem('Tenés que adjuntar foto del frente y dorso del DNI');const allowed=new Set(['image/jpeg','image/png','image/webp']);if(!allowed.has(front.mimetype)||!allowed.has(back.mimetype))throw problem('Las fotos del DNI deben ser JPG, PNG o WEBP');const hash=await bcrypt.hash(password,12);const client=await pool.connect();try{await client.query('BEGIN');const u=(await q(client,`INSERT INTO users(first_name,last_name,dni,phone,password_hash,gender) VALUES($1,$2,$3,$4,$5,$6) RETURNING *`,[String(firstName).trim(),String(lastName).trim(),clean,ph,hash,gender])).rows[0];await q(client,`INSERT INTO identity_documents(user_id,front_mime,front_data,back_mime,back_data) VALUES($1,$2,$3,$4,$5)`,[u.id,front.mimetype,front.buffer,back.mimetype,back.buffer]);for(const [type,version] of Object.entries(LEGAL_VERSIONS))await q(client,`INSERT INTO legal_acceptances(user_id,document_type,document_version,ip_address,user_agent) VALUES($1,$2,$3,$4,$5)`,[u.id,type,version,ip,userAgent]);await client.query('COMMIT');return publicUser(u);}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}}
export async function findLogin(dni,password){const clean=normalizeDni(dni);const u=(await pool.query(`SELECT * FROM users WHERE dni=$1`,[clean])).rows[0];if(!u||!(await bcrypt.compare(String(password||''),u.password_hash)))throw problem('Credenciales inválidas',401);if(u.verification_status==='rejected')throw problem('La cuenta no está habilitada',403);return u;}
export async function replaceIdentityDocuments(userId,{front=null,back=null}={}){const allowed=new Set(['image/jpeg','image/png','image/webp']);if(!front?.buffer||!back?.buffer)throw problem('Tenés que adjuntar foto del frente y dorso del DNI');if(!allowed.has(front.mimetype)||!allowed.has(back.mimetype))throw problem('Las fotos del DNI deben ser JPG, PNG o WEBP');const client=await pool.connect();try{await client.query('BEGIN');const u=(await q(client,`SELECT id,verification_status FROM users WHERE id=$1 FOR UPDATE`,[userId])).rows[0];if(!u)throw problem('Usuario inexistente',404);if(u.verification_status!=='pending')throw problem('La identidad ya no está pendiente de verificación',409);await q(client,`INSERT INTO identity_documents(user_id,front_mime,front_data,back_mime,back_data,submitted_at) VALUES($1,$2,$3,$4,$5,now()) ON CONFLICT(user_id) DO UPDATE SET front_mime=EXCLUDED.front_mime,front_data=EXCLUDED.front_data,back_mime=EXCLUDED.back_mime,back_data=EXCLUDED.back_data,submitted_at=now()`,[userId,front.mimetype,front.buffer,back.mimetype,back.buffer]);await q(client,`UPDATE users SET identity_resubmit_reason=NULL,identity_resubmit_requested_at=NULL,updated_at=now() WHERE id=$1`,[userId]);await q(client,`INSERT INTO security_events(user_id,event_type,data) VALUES($1,'identity_documents_replaced',$2::jsonb)`,[userId,JSON.stringify({submittedAt:new Date().toISOString()})]);await client.query('COMMIT');return {ok:true};}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}}

function code(){return String(crypto.randomInt(100000,1000000));}
export async function requestPasswordRecovery(dni){const clean=normalizeDni(dni);const client=await pool.connect();try{const u=(await q(client,`SELECT * FROM users WHERE dni=$1`,[clean])).rows[0];if(!u)return {ok:true};const c=code(),hash=await bcrypt.hash(c,10);await q(client,`UPDATE password_recovery_codes SET used_at=now() WHERE user_id=$1 AND used_at IS NULL`,[u.id]);const r=(await q(client,`INSERT INTO password_recovery_codes(user_id,code_hash,expires_at) VALUES($1,$2,now()+interval '15 minutes') RETURNING id`,[u.id,hash])).rows[0];await queueUserNotification(client,{userId:u.id,type:'password_recovery',title:'Recuperación de acceso',body:`Tu código de recuperación de LA RED es ${c}. Vence en 15 minutos.`,payload:{recoveryId:r.id},dedupeKey:`recovery:${r.id}`});return {ok:true};}finally{client.release();}}
export async function resetPassword(dni,otp,newPassword){if(String(newPassword||'').length<8)throw problem('La contraseña debe tener al menos 8 caracteres');const clean=normalizeDni(dni);const client=await pool.connect();try{await client.query('BEGIN');const u=(await q(client,`SELECT * FROM users WHERE dni=$1 FOR UPDATE`,[clean])).rows[0];if(!u)throw problem('Código inválido');const r=(await q(client,`SELECT * FROM password_recovery_codes WHERE user_id=$1 AND used_at IS NULL AND expires_at>now() ORDER BY id DESC LIMIT 1 FOR UPDATE`,[u.id])).rows[0];if(!r||!(await bcrypt.compare(String(otp||''),r.code_hash)))throw problem('Código inválido');const hash=await bcrypt.hash(newPassword,12);await q(client,`UPDATE users SET password_hash=$2,updated_at=now() WHERE id=$1`,[u.id,hash]);await q(client,`UPDATE password_recovery_codes SET used_at=now() WHERE id=$1`,[r.id]);await q(client,`INSERT INTO security_events(user_id,event_type) VALUES($1,'password_reset')`,[u.id]);await client.query('COMMIT');return {ok:true};}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}}
export async function requestPhoneChange(userId,newPhone){const ph=normalizePhone(newPhone);if(ph.length<8)throw problem('WhatsApp inválido');const client=await pool.connect();try{const c=code(),hash=await bcrypt.hash(c,10);await q(client,`UPDATE phone_change_codes SET used_at=now() WHERE user_id=$1 AND used_at IS NULL`,[userId]);const r=(await q(client,`INSERT INTO phone_change_codes(user_id,new_phone,code_hash,expires_at) VALUES($1,$2,$3,now()+interval '15 minutes') RETURNING id`,[userId,ph,hash])).rows[0];await q(client,`INSERT INTO notification_outbox(user_id,channel,type,payload,dedupe_key) VALUES($1,'whatsapp','phone_change',$2::jsonb,$3)`,[userId,JSON.stringify({body:`Tu código para confirmar el nuevo WhatsApp en LA RED es ${c}.`,overridePhone:ph}),`phone-change-code:${r.id}`]);return {ok:true};}finally{client.release();}}
export async function confirmPhoneChange(userId,otp){const client=await pool.connect();try{await client.query('BEGIN');const u=(await q(client,`SELECT * FROM users WHERE id=$1 FOR UPDATE`,[userId])).rows[0];const r=(await q(client,`SELECT * FROM phone_change_codes WHERE user_id=$1 AND used_at IS NULL AND expires_at>now() ORDER BY id DESC LIMIT 1 FOR UPDATE`,[userId])).rows[0];if(!r||!(await bcrypt.compare(String(otp||''),r.code_hash)))throw problem('Código inválido');const old=u.phone;await q(client,`UPDATE users SET phone=$2,updated_at=now() WHERE id=$1`,[userId,r.new_phone]);await q(client,`UPDATE phone_change_codes SET used_at=now() WHERE id=$1`,[r.id]);if(old&&old!==r.new_phone)await q(client,`INSERT INTO notification_outbox(user_id,channel,type,payload,dedupe_key) VALUES($1,'whatsapp','security_notice',$2::jsonb,$3) ON CONFLICT DO NOTHING`,[userId,JSON.stringify({body:'Aviso de seguridad de LA RED: el WhatsApp de tu cuenta fue cambiado. Si no fuiste vos, contactá al administrador.',overridePhone:old}),`phone-old-notice:${r.id}`]);await q(client,`INSERT INTO security_events(user_id,event_type,data) VALUES($1,'phone_change',$2::jsonb)`,[userId,JSON.stringify({previousPhone:old,newPhone:r.new_phone})]);await client.query('COMMIT');return {ok:true};}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}}
export async function notificationsForUser(userId){return (await pool.query(`SELECT * FROM notifications WHERE user_id=$1 ORDER BY created_at DESC LIMIT 100`,[userId])).rows;}
export async function markNotificationRead(userId,id){const r=await pool.query(`UPDATE notifications SET read_at=COALESCE(read_at,now()) WHERE id=$1 AND user_id=$2 RETURNING *`,[id,userId]);if(!r.rowCount)throw problem('Notificación inexistente',404);return r.rows[0];}
