import {pool,q} from './db.js';
import {problem} from './core.js';
import {queueUserNotification,queuePairNotification} from './notifications.js';
import {renumberCategory,recalcCategoryElos,event} from './competitionEngine.js';

export async function currentPairForUser(client,userId,{lock=false}={}){
  return (await q(client,`SELECT p.*,c.number category_number,l.slug league_slug FROM active_pair_memberships apm JOIN pairs p ON p.id=apm.pair_id JOIN categories c ON c.id=p.category_id JOIN leagues l ON l.id=p.league_id WHERE apm.user_id=$1 ${lock?'FOR UPDATE OF p':''}`,[userId])).rows[0]||null;
}
async function memberRows(client,pairId){return (await q(client,`SELECT u.id,u.first_name,u.last_name,u.phone,u.current_category_number,u.discipline_state FROM pair_members pm JOIN users u ON u.id=pm.user_id WHERE pm.pair_id=$1 ORDER BY u.id`,[pairId])).rows;}
export async function availablePartners(userId){
  const user=(await pool.query(`SELECT id,gender,verification_status,discipline_state FROM users WHERE id=$1`,[userId])).rows[0]; if(!user)throw problem('Jugador inexistente',404);
  if(user.verification_status!=='verified')return [];
  return (await pool.query(`SELECT id,first_name,last_name,current_category_number FROM users u WHERE u.role='player' AND u.id<>$1 AND u.gender=$2 AND u.verification_status='verified' AND u.discipline_state='clear' AND NOT EXISTS(SELECT 1 FROM active_pair_memberships a WHERE a.user_id=u.id) ORDER BY first_name,last_name,id`,[userId,user.gender])).rows;
}
export async function pairHub(userId){
  const client=await pool.connect();try{
    const user=(await q(client,`SELECT id,first_name,last_name,gender,verification_status,current_category_number,discipline_state FROM users WHERE id=$1`,[userId])).rows[0];
    const pair=await currentPairForUser(client,userId); if(pair)pair.members=await memberRows(client,pair.id);
    const incoming=(await q(client,`SELECT pi.*,u.first_name,u.last_name FROM pair_invitations pi JOIN users u ON u.id=pi.inviter_user_id WHERE pi.invitee_user_id=$1 AND pi.status='pending' AND pi.expires_at>now() ORDER BY pi.created_at DESC`,[userId])).rows;
    const outgoing=(await q(client,`SELECT pi.*,u.first_name,u.last_name FROM pair_invitations pi JOIN users u ON u.id=pi.invitee_user_id WHERE pi.inviter_user_id=$1 AND pi.status='pending' AND pi.expires_at>now() ORDER BY pi.created_at DESC`,[userId])).rows;
    const hasOpenAssignment=pair?Boolean((await q(client,`SELECT 1 FROM wheel_assignment_participants WHERE pair_id=$1`,[pair.id])).rowCount):false;
    const pauseRequest=pair?(await q(client,`SELECT * FROM pair_pause_requests WHERE pair_id=$1 AND status='pending' ORDER BY id DESC LIMIT 1`,[pair.id])).rows[0]||null:null;
    const dissolutionRequest=pair?(await q(client,`SELECT * FROM pair_dissolution_requests WHERE pair_id=$1 AND status IN('pending','confirmed','awaiting_result') ORDER BY id DESC LIMIT 1`,[pair.id])).rows[0]||null:null;
    return {user,pair,incoming,outgoing,available:pair?[]:await availablePartners(userId),hasOpenAssignment,pauseRequest,dissolutionRequest};
  }finally{client.release();}
}
export async function invitePartner(userId,inviteeId,requestedCategoryNumber){
  const client=await pool.connect();try{await client.query('BEGIN');
    const users=(await q(client,`SELECT id,gender,verification_status,discipline_state,current_category_number FROM users WHERE id=ANY($1::bigint[]) ORDER BY id FOR UPDATE`,[[userId,Number(inviteeId)]])).rows;if(users.length!==2)throw problem('Jugador inválido');
    const me=users.find(u=>Number(u.id)===Number(userId)), other=users.find(u=>Number(u.id)===Number(inviteeId));
    if(me.gender!==other.gender)throw problem('La pareja debe pertenecer al mismo circuito'); if(users.some(u=>u.verification_status!=='verified'))throw problem('Ambos jugadores deben estar verificados'); if(users.some(u=>u.discipline_state!=='clear'))throw problem('Hay una revisión disciplinaria abierta');
    const memberships=Number((await q(client,`SELECT count(*) n FROM active_pair_memberships WHERE user_id=ANY($1::bigint[])`,[[userId,Number(inviteeId)]])).rows[0].n);if(memberships)throw problem('Uno de los jugadores ya integra una pareja vigente');
    await q(client,`UPDATE pair_invitations SET status='expired',responded_at=now() WHERE status='pending' AND expires_at<=now()`);
    if((await q(client,`SELECT 1 FROM pair_invitations WHERE inviter_user_id=$1 AND status='pending'`,[userId])).rowCount)throw problem('Ya tenés una invitación saliente activa');
    const known=users.map(u=>u.current_category_number==null?null:Number(u.current_category_number)).filter(Number.isInteger);let category=known.length?Math.min(...known):Number(requestedCategoryNumber);if(!Number.isInteger(category)||category<1||category>7)throw problem('Elegí una categoría inicial');
    const inv=(await q(client,`INSERT INTO pair_invitations(inviter_user_id,invitee_user_id,requested_category_number,resulting_category_number) VALUES($1,$2,$3,$4) RETURNING *`,[userId,inviteeId,requestedCategoryNumber||null,category])).rows[0];
    await queueUserNotification(client,{userId:inviteeId,type:'pair_invitation',title:'Invitación de pareja',body:`Te invitaron a formar una pareja que competiría en ${category}ª.`,payload:{invitationId:inv.id},dedupeKey:`pair-invite:${inv.id}`});await client.query('COMMIT');return inv;
  }catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}}
export async function cancelInvitation(userId,id){const r=await pool.query(`UPDATE pair_invitations SET status='cancelled',responded_at=now() WHERE id=$1 AND inviter_user_id=$2 AND status='pending' RETURNING *`,[id,userId]);if(!r.rowCount)throw problem('Invitación no disponible',404);return r.rows[0];}
export async function acceptInvitation(userId,id){
  const client=await pool.connect();try{await client.query('BEGIN');const preview=(await q(client,`SELECT * FROM pair_invitations WHERE id=$1 AND invitee_user_id=$2`,[id,userId])).rows[0];if(!preview)throw problem('Invitación vencida o inexistente');
    const userIds=[Number(preview.inviter_user_id),Number(preview.invitee_user_id)];const users=(await q(client,`SELECT * FROM users WHERE id=ANY($1::bigint[]) ORDER BY id FOR UPDATE`,[userIds])).rows;if(users.some(u=>u.verification_status!=='verified'||u.discipline_state!=='clear'))throw problem('Los dos jugadores deben estar habilitados');if(users[0].gender!==users[1].gender)throw problem('Circuito incompatible');
    const inv=(await q(client,`SELECT * FROM pair_invitations WHERE id=$1 AND invitee_user_id=$2 AND status='pending' AND expires_at>now() FOR UPDATE`,[id,userId])).rows[0];if(!inv)throw problem('Invitación vencida o inexistente');
    if((await q(client,`SELECT 1 FROM active_pair_memberships WHERE user_id=ANY($1::bigint[])`,[userIds])).rowCount)throw problem('Uno de los jugadores ya integra una pareja vigente');
    const league=(await q(client,`SELECT * FROM leagues WHERE gender=$1 AND active=true`,[users[0].gender])).rows[0];const category=(await q(client,`SELECT * FROM categories WHERE league_id=$1 AND number=$2`,[league.id,inv.resulting_category_number])).rows[0];await q(client,`SELECT id FROM categories WHERE id=$1 FOR UPDATE`,[category.id]);
    let pair=(await q(client,`SELECT p.* FROM pairs p WHERE p.competition_state='inactive' AND p.league_id=$1 AND (SELECT array_agg(pm.user_id ORDER BY pm.user_id) FROM pair_members pm WHERE pm.pair_id=p.id)=$2::bigint[] ORDER BY p.id DESC LIMIT 1 FOR UPDATE`,[league.id,[...userIds].sort((a,b)=>a-b)])).rows[0];
    if(pair){await q(client,`UPDATE pairs SET competition_state='active',archived_at=NULL,category_id=$2,position=999999,waiting_since=now(),consecutive_wins=0,consecutive_losses=0,first_place_defenses=0 WHERE id=$1`,[pair.id,category.id]);}
    else{pair=(await q(client,`INSERT INTO pairs(league_id,category_id,position,waiting_since) VALUES($1,$2,999999,now()) RETURNING *`,[league.id,category.id])).rows[0];for(const uid of userIds)await q(client,`INSERT INTO pair_members(pair_id,user_id) VALUES($1,$2)`,[pair.id,uid]);}
    for(const uid of userIds){await q(client,`INSERT INTO active_pair_memberships(user_id,pair_id) VALUES($1,$2)`,[uid,pair.id]);await q(client,`UPDATE users SET current_category_number=COALESCE(current_category_number,$2),updated_at=now() WHERE id=$1`,[uid,Number(inv.resulting_category_number)]);}
    await renumberCategory(client,category.id);await recalcCategoryElos(client,category.id);await q(client,`UPDATE pair_invitations SET status='accepted',responded_at=now() WHERE id=$1`,[inv.id]);await q(client,`UPDATE pair_invitations SET status='invalidated',responded_at=now() WHERE status='pending' AND id<>$2 AND (inviter_user_id=ANY($1::bigint[]) OR invitee_user_id=ANY($1::bigint[]))`,[userIds,inv.id]);await event(client,`pair-formed:${pair.id}:${inv.id}`,'pair_formed',{pairId:pair.id,data:{category:Number(inv.resulting_category_number)}});await client.query('COMMIT');return pair;
  }catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}}
export async function requestPause(userId,afterCurrent=false){const client=await pool.connect();try{await client.query('BEGIN');const pair=await currentPairForUser(client,userId,{lock:true});if(!pair)throw problem('No tenés pareja vigente');if(pair.competition_state!=='active'||pair.discipline_state!=='clear')throw problem('La pareja no puede pausar en este estado');const members=await memberRows(client,pair.id);if(members.some(m=>m.discipline_state!=='clear'))throw problem('Hay una revisión disciplinaria individual pendiente');const open=(await q(client,`SELECT 1 FROM wheel_assignment_participants WHERE pair_id=$1`,[pair.id])).rowCount;if(open&&!afterCurrent)throw problem('Usá “pausar al terminar este partido”');let r=(await q(client,`SELECT * FROM pair_pause_requests WHERE pair_id=$1 AND status='pending' FOR UPDATE`,[pair.id])).rows[0];if(!r)r=(await q(client,`INSERT INTO pair_pause_requests(pair_id,requested_by_user_id,effective_after_current) VALUES($1,$2,$3) RETURNING *`,[pair.id,userId,Boolean(afterCurrent)])).rows[0];else if(Number(r.requested_by_user_id)!==Number(userId)){await q(client,`UPDATE pair_pause_requests SET status='confirmed',resolved_at=now() WHERE id=$1`,[r.id]);if(open){await q(client,`UPDATE pairs SET pause_after_current=true WHERE id=$1`,[pair.id]);}else{await q(client,`UPDATE pairs SET competition_state='paused',elo=0,waiting_since=NULL,first_place_defenses=CASE WHEN position=1 AND (SELECT number FROM categories WHERE id=pairs.category_id)=1 THEN 0 ELSE first_place_defenses END WHERE id=$1`,[pair.id]);await renumberCategory(client,pair.category_id);await recalcCategoryElos(client,pair.category_id);}r.status='confirmed';}
    await queuePairNotification(client,pair.id,{type:'pause_request',title:'Pausa de pareja',body:'Hay una solicitud de pausa pendiente de la confirmación del compañero.',payload:{pairId:pair.id},dedupeKey:`pause:${r.id}`});await client.query('COMMIT');return r;}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}}
export async function reactivatePair(userId){const client=await pool.connect();try{await client.query('BEGIN');const pair=await currentPairForUser(client,userId,{lock:true});if(!pair||pair.competition_state!=='paused')throw problem('La pareja no está pausada');await q(client,`UPDATE pairs SET competition_state='active',waiting_since=now(),monthly_miss_streak=CASE WHEN monthly_miss_streak>=2 THEN 0 ELSE monthly_miss_streak END,position=999999 WHERE id=$1`,[pair.id]);await renumberCategory(client,pair.category_id);await recalcCategoryElos(client,pair.category_id);await client.query('COMMIT');return {ok:true};}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}}
export async function requestDissolution(userId){const client=await pool.connect();try{await client.query('BEGIN');const pair=await currentPairForUser(client,userId,{lock:true});if(!pair)throw problem('No tenés pareja vigente');if(pair.discipline_state!=='clear')throw problem('La pareja debe resolver su disciplina antes de disolverse');const members=await memberRows(client,pair.id);if(members.some(m=>m.discipline_state!=='clear'))throw problem('Hay disciplina individual pendiente');let r=(await q(client,`SELECT * FROM pair_dissolution_requests WHERE pair_id=$1 AND status IN('pending','confirmed','awaiting_result') FOR UPDATE`,[pair.id])).rows[0];if(!r)r=(await q(client,`INSERT INTO pair_dissolution_requests(pair_id,requested_by_user_id) VALUES($1,$2) RETURNING *`,[pair.id,userId])).rows[0];else if(Number(r.requested_by_user_id)!==Number(userId)){await q(client,`UPDATE pair_dissolution_requests SET status='confirmed' WHERE id=$1`,[r.id]);r.status='confirmed';}
    await queuePairNotification(client,pair.id,{type:'dissolution_request',title:'Solicitud de disolución',body:'Hay una solicitud de disolución. Las obligaciones abiertas se resuelven antes de archivar la pareja.',payload:{pairId:pair.id},dedupeKey:`dissolve:${r.id}`});await client.query('COMMIT');return r;}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}}
export async function archivePair(client,pairId){const p=(await q(client,`SELECT * FROM pairs WHERE id=$1 FOR UPDATE`,[pairId])).rows[0];if(!p)return;await q(client,`DELETE FROM active_pair_memberships WHERE pair_id=$1`,[pairId]);await q(client,`UPDATE pairs SET competition_state='inactive',archived_at=now(),waiting_since=NULL,pause_after_current=false,consecutive_wins=0,consecutive_losses=0,first_place_defenses=0,elo=0 WHERE id=$1`,[pairId]);await renumberCategory(client,p.category_id);await recalcCategoryElos(client,p.category_id);}
