import {pool,q} from './db.js';
import {problem,validResponsibilityProposal,resultEquals,normalizeScore} from './core.js';
import {queueAssignmentNotification,queuePairNotification} from './notifications.js';
import {currentPairForUser,archivePair} from './pairs.js';
import {event,applyPositionPenalties,applySportingResult,recalcCategoryElos,renumberCategory} from './competitionEngine.js';

function effectiveDeadline(a){return a.extraordinary_used&&a.extraordinary_deadline_at?a.extraordinary_deadline_at:a.deadline_at;}
async function settings(client){const rows=(await q(client,`SELECT key,value FROM app_settings`)).rows;return Object.fromEntries(rows.map(r=>[r.key,r.value]));}
async function assignmentForPair(client,pairId,{lock=false}={}){return (await q(client,`SELECT wa.* FROM wheel_assignment_participants wap JOIN wheel_assignments wa ON wa.id=wap.assignment_id WHERE wap.pair_id=$1 ${lock?'FOR UPDATE OF wa':''}`,[pairId])).rows[0]||null;}
async function rivalSummary(client,a,pairId){const id=Number(a.pair_a_id)===Number(pairId)?a.pair_b_id:a.pair_a_id;const pair=(await q(client,`SELECT p.id,p.position,c.number category_number,string_agg(u.first_name||' '||u.last_name,' / ' ORDER BY u.id) players FROM pairs p JOIN categories c ON c.id=p.category_id JOIN pair_members pm ON pm.pair_id=p.id JOIN users u ON u.id=pm.user_id WHERE p.id=$1 GROUP BY p.id,c.number`,[id])).rows[0];pair.members=(await q(client,`SELECT u.id,u.first_name,u.last_name,u.phone FROM pair_members pm JOIN users u ON u.id=pm.user_id WHERE pm.pair_id=$1 ORDER BY u.id`,[id])).rows;return pair;}
async function myPairSummary(client,pair){const row=(await q(client,`SELECT p.*,c.number category_number,l.slug league_slug,string_agg(u.first_name||' '||u.last_name,' / ' ORDER BY u.id) players FROM pairs p JOIN categories c ON c.id=p.category_id JOIN leagues l ON l.id=p.league_id JOIN pair_members pm ON pm.pair_id=p.id JOIN users u ON u.id=pm.user_id WHERE p.id=$1 GROUP BY p.id,c.number,l.slug`,[pair.id])).rows[0];return row;}
export async function myLeague(userId){const client=await pool.connect();try{const user=(await q(client,`SELECT id,first_name,last_name,verification_status,discipline_state,identity_resubmit_reason,identity_resubmit_requested_at FROM users WHERE id=$1`,[userId])).rows[0];const pair=await currentPairForUser(client,userId);if(!pair)return {user,pair:null,assignment:null,recentEvents:[]};const summary=await myPairSummary(client,pair);let a=await assignmentForPair(client,pair.id);if(a){a.rival=await rivalSummary(client,a,pair.id);a.pendingProposal=(await q(client,`SELECT wsp.*,v.name venue_name FROM wheel_schedule_proposals wsp JOIN venues v ON v.id=wsp.venue_id WHERE wsp.assignment_id=$1 AND wsp.status='pending' ORDER BY wsp.id DESC LIMIT 1`,[a.id])).rows[0]||null;a.myVersion=(await q(client,`SELECT * FROM wheel_result_versions WHERE assignment_id=$1 AND pair_id=$2`,[a.id,pair.id])).rows[0]||null;a.otherVersion=(await q(client,`SELECT * FROM wheel_result_versions WHERE assignment_id=$1 AND pair_id<>$2`,[a.id,pair.id])).rows[0]||null;a.noShow=(await q(client,`SELECT * FROM wheel_no_shows WHERE assignment_id=$1`,[a.id])).rows[0]||null;a.extensionVotes=(await q(client,`SELECT pair_id FROM wheel_extension_votes WHERE assignment_id=$1`,[a.id])).rows.map(r=>Number(r.pair_id));}
const recent=(await q(client,`SELECT event_type,data,created_at FROM competitive_events WHERE pair_id=$1 ORDER BY created_at DESC,id DESC LIMIT 15`,[pair.id])).rows;return {user,pair:summary,assignment:a,recentEvents:recent};}finally{client.release();}}

async function lastMeetings(client,pairIds){const rows=(await q(client,`SELECT LEAST(pair_a_id,pair_b_id) a,GREATEST(pair_a_id,pair_b_id) b,max(played_at) last FROM matches WHERE pair_a_id=ANY($1::bigint[]) OR pair_b_id=ANY($1::bigint[]) GROUP BY 1,2`,[pairIds])).rows;const m=new Map();for(const r of rows)m.set(`${r.a}:${r.b}`,r.last);return m;}
async function createAssignmentsForCategory(client,categoryId){
  const eligible=(await q(client,`SELECT p.id,p.waiting_since,p.position,p.league_id FROM pairs p WHERE p.category_id=$1 AND p.competition_state='active' AND p.discipline_state='clear' AND p.pause_after_current=false AND NOT EXISTS(SELECT 1 FROM pair_members pm JOIN users u ON u.id=pm.user_id WHERE pm.pair_id=p.id AND u.discipline_state<>'clear') AND NOT EXISTS(SELECT 1 FROM wheel_assignment_participants wap WHERE wap.pair_id=p.id) AND NOT EXISTS(SELECT 1 FROM pair_dissolution_requests d WHERE d.pair_id=p.id AND d.status IN('pending','confirmed','awaiting_result')) ORDER BY COALESCE(p.waiting_since,p.created_at),p.position,p.id FOR UPDATE`,[categoryId])).rows;if(eligible.length<2)return 0;
  const ids=eligible.map(r=>Number(r.id));const meetings=await lastMeetings(client,ids);const available=[...eligible];if(available.length%2===1)available.pop();let created=0;
  while(available.length>=2){const first=available.shift();available.sort((x,y)=>{const k1=`${Math.min(first.id,x.id)}:${Math.max(first.id,x.id)}`,k2=`${Math.min(first.id,y.id)}:${Math.max(first.id,y.id)}`;const a=meetings.get(k1)||null,b=meetings.get(k2)||null;if(a===null&&b!==null)return -1;if(a!==null&&b===null)return 1;if(a&&b){const d=new Date(a)-new Date(b);if(d)return d;}return Number(x.id)-Number(y.id);});const second=available.shift();const a=(await q(client,`INSERT INTO wheel_assignments(league_id,category_id,pair_a_id,pair_b_id) VALUES($1,$2,$3,$4) RETURNING *`,[first.league_id,categoryId,first.id,second.id])).rows[0];await q(client,`INSERT INTO wheel_assignment_participants(assignment_id,pair_id) VALUES($1,$2),($1,$3)`,[a.id,first.id,second.id]);await q(client,`UPDATE pairs SET waiting_since=NULL WHERE id=ANY($1::bigint[])`,[[first.id,second.id]]);await event(client,`assignment:${a.id}`,'assignment_created',{assignmentId:a.id,data:{pairA:first.id,pairB:second.id}});await queueAssignmentNotification(client,a,{type:'assignment',title:'Nuevo rival',body:'La rueda de LA RED asignó un nuevo partido. Tienen 30 días para jugar y cargar el resultado.',payload:{assignmentId:a.id},dedupeKey:`assignment:${a.id}`});created++;}
  return created;
}
export async function assignWheel(){const client=await pool.connect();try{await client.query('BEGIN');await client.query('SELECT pg_advisory_xact_lock(8675309)');const s=await settings(client);if(s.league_clock_paused===true){await client.query('COMMIT');return {created:0,paused:true};}const cats=(await q(client,`SELECT id FROM categories ORDER BY league_id,number`)).rows;let created=0;for(const c of cats)created+=await createAssignmentsForCategory(client,c.id);await client.query('COMMIT');return {created};}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}}

export async function proposeSchedule(userId,assignmentId,{scheduledAt,venueId}){const client=await pool.connect();try{await client.query('BEGIN');const pair=await currentPairForUser(client,userId);if(!pair)throw problem('No tenés pareja');const a=await assignmentForPair(client,pair.id,{lock:true});if(!a||Number(a.id)!==Number(assignmentId)||a.status!=='open')throw problem('Partido no disponible');const when=new Date(scheduledAt);if(Number.isNaN(when.getTime())||when.getTime()<=Date.now())throw problem('Fecha inválida');if(when.getTime()>new Date(effectiveDeadline(a)).getTime())throw problem('La propuesta supera el plazo del partido');const venue=(await q(client,`SELECT * FROM venues WHERE id=$1 AND active=true`,[venueId])).rows[0];if(!venue)throw problem('Cancha no disponible');await q(client,`UPDATE wheel_schedule_proposals SET status='replaced',responded_at=now() WHERE assignment_id=$1 AND status='pending'`,[a.id]);const p=(await q(client,`INSERT INTO wheel_schedule_proposals(assignment_id,proposed_by_pair_id,scheduled_at,venue_id) VALUES($1,$2,$3,$4) RETURNING *`,[a.id,pair.id,when,venue.id])).rows[0];await event(client,`schedule-proposal:${p.id}`,'schedule_proposed',{pairId:pair.id,userId,assignmentId:a.id,data:{scheduledAt:p.scheduled_at,venueId:venue.id}});await queueAssignmentNotification(client,a,{type:'schedule_proposal',title:'Nueva propuesta',body:`Hay una nueva propuesta de fecha y lugar para el partido. La pareja rival tiene 48 horas para responder.`,payload:{assignmentId:a.id,proposalId:p.id},dedupeKey:`schedule:${p.id}`});await client.query('COMMIT');return p;}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}}
export async function acceptSchedule(userId,assignmentId,proposalId){const client=await pool.connect();try{await client.query('BEGIN');const pair=await currentPairForUser(client,userId);const a=pair&&await assignmentForPair(client,pair.id,{lock:true});if(!a||Number(a.id)!==Number(assignmentId))throw problem('Partido no disponible');const p=(await q(client,`SELECT * FROM wheel_schedule_proposals WHERE id=$1 AND assignment_id=$2 AND status='pending' AND response_deadline_at>now() FOR UPDATE`,[proposalId,a.id])).rows[0];if(!p)throw problem('Propuesta vencida o inexistente');if(Number(p.proposed_by_pair_id)===Number(pair.id))throw problem('La otra pareja debe aceptar');await q(client,`UPDATE wheel_schedule_proposals SET status='accepted',responded_at=now() WHERE id=$1`,[p.id]);await q(client,`UPDATE wheel_assignments SET scheduled_at=$2,venue_id=$3,schedule_confirmed_at=now() WHERE id=$1`,[a.id,p.scheduled_at,p.venue_id]);await event(client,`schedule-accepted:${p.id}`,'schedule_accepted',{pairId:pair.id,userId,assignmentId:a.id,data:{scheduledAt:p.scheduled_at,venueId:p.venue_id}});await queueAssignmentNotification(client,a,{type:'schedule_confirmed',title:'Partido confirmado',body:'La fecha, hora y cancha quedaron confirmadas por ambas parejas.',payload:{assignmentId:a.id},dedupeKey:`schedule-confirmed:${p.id}`});await client.query('COMMIT');return {ok:true};}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}}
export async function voteExtension(userId,assignmentId){const client=await pool.connect();try{await client.query('BEGIN');const pair=await currentPairForUser(client,userId);const a=pair&&await assignmentForPair(client,pair.id,{lock:true});if(!a||Number(a.id)!==Number(assignmentId)||a.status!=='open')throw problem('Partido no disponible');if(a.extraordinary_used)throw problem('La extensión extraordinaria ya fue usada');if(Date.now()<new Date(a.deadline_at).getTime())throw problem('La extensión extraordinaria se habilita cuando vence el plazo original');const inserted=(await q(client,`INSERT INTO wheel_extension_votes(assignment_id,pair_id) VALUES($1,$2) ON CONFLICT DO NOTHING RETURNING pair_id`,[a.id,pair.id])).rows[0];const votes=Number((await q(client,`SELECT count(*) n FROM wheel_extension_votes WHERE assignment_id=$1`,[a.id])).rows[0].n);if(inserted&&votes===1)await queueAssignmentNotification(client,a,{type:'extension_vote',title:'Causa externa pendiente',body:'Una pareja confirmó causa externa. Falta la confirmación de la otra para activar 15 días adicionales.',payload:{assignmentId:a.id},dedupeKey:`extension-vote:${a.id}`});if(votes>=2){const ext=new Date(new Date(a.deadline_at).getTime()+15*24*60*60*1000);await q(client,`UPDATE wheel_assignments SET extraordinary_used=true,extraordinary_deadline_at=$2 WHERE id=$1`,[a.id,ext]);await event(client,`extension:${a.id}`,'extraordinary_extension',{assignmentId:a.id,data:{until:ext}});await queueAssignmentNotification(client,a,{type:'extension_confirmed',title:'Extensión extraordinaria',body:'Ambas parejas confirmaron la causa externa. El partido tiene 15 días adicionales.',payload:{assignmentId:a.id},dedupeKey:`extension-confirmed:${a.id}`});}await client.query('COMMIT');return {votes,activated:votes>=2};}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}}
export async function reportNoShow(userId,assignmentId){const client=await pool.connect();try{await client.query('BEGIN');const pair=await currentPairForUser(client,userId);const a=pair&&await assignmentForPair(client,pair.id,{lock:true});if(!a||Number(a.id)!==Number(assignmentId)||a.status!=='open'||!a.schedule_confirmed_at||!a.scheduled_at)throw problem('No hay una programación oficial');if(Date.now()<new Date(a.scheduled_at).getTime())throw problem('El no-show se habilita después del horario oficial');const reported=Number(a.pair_a_id)===Number(pair.id)?a.pair_b_id:a.pair_a_id;const row=(await q(client,`INSERT INTO wheel_no_shows(assignment_id,reported_by_pair_id,reported_pair_id) VALUES($1,$2,$3) ON CONFLICT(assignment_id) DO NOTHING RETURNING *`,[a.id,pair.id,reported])).rows[0];if(!row)throw problem('Ya existe un no-show informado');await queueAssignmentNotification(client,a,{type:'no_show',title:'No-show reportado',body:'Se informó un no-show. La pareja reportada tiene 48 horas para objetar.',payload:{assignmentId:a.id},dedupeKey:`no-show:${a.id}`});await client.query('COMMIT');return row;}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}}
export async function contestNoShow(userId,assignmentId){const client=await pool.connect();try{await client.query('BEGIN');const pair=await currentPairForUser(client,userId);const a=pair&&await assignmentForPair(client,pair.id,{lock:true});if(!a||Number(a.id)!==Number(assignmentId))throw problem('Partido no disponible');const n=(await q(client,`SELECT * FROM wheel_no_shows WHERE assignment_id=$1 AND reported_pair_id=$2 AND status='pending' AND response_deadline_at>now() FOR UPDATE`,[a.id,pair.id])).rows[0];if(!n)throw problem('No-show no disponible para objetar');await q(client,`UPDATE wheel_no_shows SET status='contested',responded_at=now() WHERE id=$1`,[n.id]);await applyPositionPenalties(client,[a.pair_a_id,a.pair_b_id],{sourceKey:`no-show-contested:${a.id}`});await closeAssignment(client,a,'expired','no_show_contested');await client.query('COMMIT');return {ok:true};}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}}
function resultPayload(raw,a,pairId){
  const resultType=raw.resultType==='injury_abandonment'?'injury_abandonment':'normal';
  const winner=Number(raw.winnerPairId);if(![Number(a.pair_a_id),Number(a.pair_b_id)].includes(winner))throw problem('Ganador inválido');
  const playedAt=new Date(raw.playedAt);if(Number.isNaN(playedAt.getTime())||playedAt.getTime()>Date.now()+5*60*1000)throw problem('Fecha jugada inválida');
  if(playedAt.getTime()<new Date(a.assigned_at).getTime()-5*60*1000||playedAt.getTime()>new Date(effectiveDeadline(a)).getTime())throw problem('La fecha jugada está fuera del plazo del compromiso');
  let score=null,abandoned=null;
  if(resultType==='normal'){
    score=normalizeScore(raw.score);
    const aSets=score.sets.filter(s=>s.pairA>s.pairB).length,bSets=score.sets.length-aSets;
    const scoreWinner=aSets>bSets?Number(a.pair_a_id):Number(a.pair_b_id);
    if(scoreWinner!==winner)throw problem('El ganador elegido no coincide con el marcador');
  }else{
    abandoned=Number(raw.abandonedPairId);if(![Number(a.pair_a_id),Number(a.pair_b_id)].includes(abandoned)||abandoned===winner)throw problem('Pareja que abandonó inválida');
  }
  return {winner_pair_id:winner,result_type:resultType,played_at:playedAt,score,abandoned_pair_id:abandoned,pair_id:pairId};
}
export async function closeAssignment(client,a,status,reason){await q(client,`UPDATE wheel_assignments SET status=$2,closed_at=now(),close_reason=$3 WHERE id=$1`,[a.id,status,reason]);await q(client,`DELETE FROM wheel_assignment_participants WHERE assignment_id=$1`,[a.id]);for(const pid of [a.pair_a_id,a.pair_b_id]){const p=(await q(client,`SELECT pause_after_current,category_id,competition_state FROM pairs WHERE id=$1 FOR UPDATE`,[pid])).rows[0];if(p?.pause_after_current){await q(client,`UPDATE pairs SET competition_state='paused',pause_after_current=false,elo=0,waiting_since=NULL,first_place_defenses=CASE WHEN position=1 AND (SELECT number FROM categories WHERE id=pairs.category_id)=1 THEN 0 ELSE first_place_defenses END WHERE id=$1`,[pid]);await renumberCategory(client,p.category_id);await recalcCategoryElos(client,p.category_id);}else if(p?.competition_state==='active'){await q(client,`UPDATE pairs SET waiting_since=now() WHERE id=$1`,[pid]);}}
}
async function finalizeVersion(client,a,version,source){const match=await applySportingResult(client,{assignment:a,winnerPairId:version.winner_pair_id,resultType:version.result_type,score:version.score,playedAt:version.played_at,source});await closeAssignment(client,a,'confirmed',source);await queueAssignmentNotification(client,a,{type:'result_confirmed',title:'Resultado confirmado',body:'El resultado quedó oficial y el motor competitivo ya aplicó sus consecuencias.',payload:{assignmentId:a.id},dedupeKey:`result-confirmed:${a.id}`});return match;}
export async function submitResult(userId,assignmentId,raw){const client=await pool.connect();try{await client.query('BEGIN');const pair=await currentPairForUser(client,userId);const a=pair&&await assignmentForPair(client,pair.id,{lock:true});if(!a||Number(a.id)!==Number(assignmentId)||!['open','result_pending'].includes(a.status))throw problem('Partido no disponible');if(a.status==='open'&&Date.now()>new Date(effectiveDeadline(a)).getTime())throw problem('Venció el plazo para jugar y cargar el resultado',409);if(a.status==='result_pending'&&a.confirmation_deadline_at&&Date.now()>new Date(a.confirmation_deadline_at).getTime()){const versions=(await q(client,`SELECT * FROM wheel_result_versions WHERE assignment_id=$1`,[a.id])).rows;if(versions.length===1){const m=await finalizeVersion(client,a,versions[0],'silence_15_days');await client.query('COMMIT');return {status:'confirmed',autoValidated:true,match:m};}}
  const pendingNoShow=(await q(client,`SELECT 1 FROM wheel_no_shows WHERE assignment_id=$1 AND status='pending'`,[a.id])).rowCount;if(pendingNoShow)throw problem('Primero debe resolverse el no-show informado');
  const mine=resultPayload(raw,a,pair.id);const existing=(await q(client,`SELECT * FROM wheel_result_versions WHERE assignment_id=$1 AND pair_id=$2 FOR UPDATE`,[a.id,pair.id])).rows[0];const other=(await q(client,`SELECT * FROM wheel_result_versions WHERE assignment_id=$1 AND pair_id<>$2 FOR UPDATE`,[a.id,pair.id])).rows[0];if(existing&&other)throw problem('Las versiones ya están congeladas');if(existing){await q(client,`UPDATE wheel_result_versions SET winner_pair_id=$3,result_type=$4,played_at=$5,score=$6::jsonb,abandoned_pair_id=$7,version_no=version_no+1,updated_at=now() WHERE id=$1 AND pair_id=$2`,[existing.id,pair.id,mine.winner_pair_id,mine.result_type,mine.played_at,JSON.stringify(mine.score),mine.abandoned_pair_id]);await event(client,`result-revised:${a.id}:${pair.id}:${existing.version_no+1}`,'result_revised',{pairId:pair.id,userId,assignmentId:a.id});}else{await q(client,`INSERT INTO wheel_result_versions(assignment_id,pair_id,winner_pair_id,result_type,played_at,score,abandoned_pair_id) VALUES($1,$2,$3,$4,$5,$6::jsonb,$7)`,[a.id,pair.id,mine.winner_pair_id,mine.result_type,mine.played_at,JSON.stringify(mine.score),mine.abandoned_pair_id]);await event(client,`result-submitted:${a.id}:${pair.id}`,'result_submitted',{pairId:pair.id,userId,assignmentId:a.id});}
  const versions=(await q(client,`SELECT * FROM wheel_result_versions WHERE assignment_id=$1 ORDER BY id`,[a.id])).rows;if(versions.length===1){await q(client,`UPDATE wheel_assignments SET status='result_pending',confirmation_deadline_at=COALESCE(confirmation_deadline_at,now()+interval '15 days') WHERE id=$1`,[a.id]);await queueAssignmentNotification(client,a,{type:'result_pending',title:'Resultado cargado',body:'Se cargó una versión del resultado. La otra pareja tiene 15 días para confirmar o cargar su versión.',payload:{assignmentId:a.id},dedupeKey:`result-pending:${a.id}`});await client.query('COMMIT');return {status:'result_pending'};}
  const v1=versions[0],v2=versions[1];if(resultEquals(v1,v2)){const m=await finalizeVersion(client,a,v1,'matching_versions');await client.query('COMMIT');return {status:'confirmed',match:m};}await q(client,`UPDATE wheel_assignments SET status='disputed' WHERE id=$1`,[a.id]);await queueAssignmentNotification(client,a,{type:'result_disputed',title:'Resultado en disputa',body:'Las parejas cargaron versiones diferentes. Administración resolverá cuál versión es válida o cerrará el partido sin resultado.',payload:{assignmentId:a.id},dedupeKey:`result-disputed:${a.id}`});await client.query('COMMIT');return {status:'disputed'};
 }catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}}
export async function confirmResult(userId,assignmentId){const client=await pool.connect();try{await client.query('BEGIN');const pair=await currentPairForUser(client,userId);const a=pair&&await assignmentForPair(client,pair.id,{lock:true});if(!a||Number(a.id)!==Number(assignmentId)||a.status!=='result_pending')throw problem('Resultado no disponible');if(a.confirmation_deadline_at&&Date.now()>new Date(a.confirmation_deadline_at).getTime()){const vs=(await q(client,`SELECT * FROM wheel_result_versions WHERE assignment_id=$1`,[a.id])).rows;if(vs.length===1){const m=await finalizeVersion(client,a,vs[0],'silence_15_days');await client.query('COMMIT');return {status:'confirmed',autoValidated:true,match:m};}}
 const mine=(await q(client,`SELECT 1 FROM wheel_result_versions WHERE assignment_id=$1 AND pair_id=$2`,[a.id,pair.id])).rowCount;if(mine)throw problem('Tu pareja cargó la versión inicial');const v=(await q(client,`SELECT * FROM wheel_result_versions WHERE assignment_id=$1 LIMIT 1`,[a.id])).rows[0];if(!v)throw problem('No hay resultado para confirmar');const m=await finalizeVersion(client,a,v,'opponent_confirmed');await client.query('COMMIT');return {status:'confirmed',match:m};}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}}

async function expireAssignment(client,a){
  const n=(await q(client,`SELECT * FROM wheel_no_shows WHERE assignment_id=$1 FOR UPDATE`,[a.id])).rows[0];
  if(n?.status==='pending'){
    if(Date.now()<=new Date(n.response_deadline_at).getTime())return;
    await applyPositionPenalties(client,[n.reported_pair_id],{sourceKey:`no-show-silence:${a.id}`});
    await q(client,`UPDATE pairs SET monthly_miss_streak=monthly_miss_streak+1 WHERE id=$1`,[n.reported_pair_id]);
    await q(client,`UPDATE pairs SET monthly_miss_streak=0 WHERE id=$1`,[n.reported_by_pair_id]);
    await q(client,`UPDATE wheel_no_shows SET status='accepted',responded_at=now() WHERE id=$1`,[n.id]);await closeAssignment(client,a,'expired','no_show_silence');return;
  }
  if(a.status==='result_pending'&&a.confirmation_deadline_at&&Date.now()>new Date(a.confirmation_deadline_at).getTime()){const vs=(await q(client,`SELECT * FROM wheel_result_versions WHERE assignment_id=$1`,[a.id])).rows;if(vs.length===1){await finalizeVersion(client,a,vs[0],'silence_15_days');return;}}
  if(a.status!=='open'||Date.now()<=new Date(effectiveDeadline(a)).getTime())return;
  if(!a.extraordinary_used && Date.now()<=new Date(a.deadline_at).getTime()+48*60*60*1000){
    await queueAssignmentNotification(client,a,{type:'extension_window',title:'Venció el plazo original',body:'Si una causa externa impidió jugar, ambas parejas tienen 48 horas para confirmar la única extensión extraordinaria de 15 días. Durante esta ventana no se puede jugar/cargar sin que la extensión quede activada.',payload:{assignmentId:a.id},dedupeKey:`extension-window:${a.id}`});
    return;
  }
  const proposals=(await q(client,`SELECT proposed_by_pair_id,created_at FROM wheel_schedule_proposals WHERE assignment_id=$1`,[a.id])).rows;const actors=new Set(proposals.filter(p=>validResponsibilityProposal(p.created_at,effectiveDeadline(a))).map(p=>Number(p.proposed_by_pair_id)));let penalized,compliant=[];
  if(!a.schedule_confirmed_at&&actors.size===1){const actor=[...actors][0];penalized=[Number(a.pair_a_id),Number(a.pair_b_id)].filter(x=>x!==actor);compliant=[actor];}else penalized=[Number(a.pair_a_id),Number(a.pair_b_id)];
  const extraFailure=a.extraordinary_used;if(extraFailure){penalized=[Number(a.pair_a_id),Number(a.pair_b_id)];compliant=[];}await applyPositionPenalties(client,penalized,{sourceKey:`assignment-expiry:${a.id}`});if(!extraFailure){for(const pid of penalized)await q(client,`UPDATE pairs SET monthly_miss_streak=monthly_miss_streak+1 WHERE id=$1`,[pid]);for(const pid of compliant)await q(client,`UPDATE pairs SET monthly_miss_streak=0 WHERE id=$1`,[pid]);}
  await closeAssignment(client,a,'expired',extraFailure?'extraordinary_expired':'deadline_expired');
}
async function applyAutoPauses(client){const rows=(await q(client,`SELECT id,category_id FROM pairs WHERE competition_state='active' AND monthly_miss_streak>=2 AND NOT EXISTS(SELECT 1 FROM wheel_assignment_participants w WHERE w.pair_id=pairs.id) FOR UPDATE`)).rows;for(const p of rows){await q(client,`UPDATE pairs SET competition_state='paused',elo=0,waiting_since=NULL,first_place_defenses=CASE WHEN position=1 AND (SELECT number FROM categories WHERE id=pairs.category_id)=1 THEN 0 ELSE first_place_defenses END WHERE id=$1`,[p.id]);await renumberCategory(client,p.category_id);await recalcCategoryElos(client,p.category_id);await event(client,`auto-pause:${p.id}:${Date.now()}`,'auto_pause',{pairId:p.id});await queuePairNotification(client,p.id,{type:'auto_pause',title:'Pareja pausada',body:'La pareja quedó pausada automáticamente después de dos incumplimientos atribuibles consecutivos.',payload:{pairId:p.id},dedupeKey:`auto-pause:${p.id}:${new Date().toISOString().slice(0,10)}`});}}
async function processDissolutions(client){
  const requests=(await q(client,`SELECT d.*,p.category_id FROM pair_dissolution_requests d JOIN pairs p ON p.id=d.pair_id WHERE d.status IN('confirmed','pending','awaiting_result') ORDER BY d.id FOR UPDATE OF d`)).rows;
  for(const d of requests){
    const a=await assignmentForPair(client,d.pair_id,{lock:true});
    const deadlinePassed=Date.now()>=new Date(d.deadline_at).getTime();
    if(a){
      const versions=(await q(client,`SELECT * FROM wheel_result_versions WHERE assignment_id=$1`,[a.id])).rows;
      if(versions.length){await q(client,`UPDATE pair_dissolution_requests SET status='awaiting_result' WHERE id=$1`,[d.id]);continue;}
      if(!deadlinePassed){if(d.status==='confirmed')await q(client,`UPDATE pair_dissolution_requests SET status='awaiting_result' WHERE id=$1`,[d.id]);continue;}
      const rival=Number(a.pair_a_id)===Number(d.pair_id)?a.pair_b_id:a.pair_a_id;
      const pseudo={winner_pair_id:rival,result_type:'dissolution_forfeit',played_at:new Date(),score:null,abandoned_pair_id:null};
      await finalizeVersion(client,a,pseudo,'dissolution_forfeit');
      await archivePair(client,d.pair_id);await q(client,`UPDATE pair_dissolution_requests SET status='applied',resolved_at=now() WHERE id=$1`,[d.id]);continue;
    }
    if(d.status==='confirmed'||d.status==='awaiting_result'||deadlinePassed){await archivePair(client,d.pair_id);await q(client,`UPDATE pair_dissolution_requests SET status='applied',resolved_at=now() WHERE id=$1`,[d.id]);}
  }
}
export async function maintenance(){const client=await pool.connect();try{await client.query('BEGIN');await client.query('SELECT pg_advisory_xact_lock(8675310)');const s=await settings(client);if(s.league_clock_paused===true){await client.query('COMMIT');return {paused:true};}await q(client,`UPDATE pair_invitations SET status='expired',responded_at=now() WHERE status='pending' AND expires_at<=now()`);await q(client,`UPDATE wheel_schedule_proposals SET status='expired',responded_at=now() WHERE status='pending' AND response_deadline_at<=now()`);const assignments=(await q(client,`SELECT * FROM wheel_assignments WHERE status IN('open','result_pending') ORDER BY id FOR UPDATE`)).rows;for(const a of assignments)await expireAssignment(client,a);await applyAutoPauses(client);await processDissolutions(client);await client.query('COMMIT');const assigned=await assignWheel();return {ok:true,assigned:assigned.created||0};}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}}

export async function publicUpcoming(){return (await pool.query(`SELECT wa.id,wa.scheduled_at,l.slug,c.number category_number,v.name venue_name,v.address,string_agg(DISTINCT CASE WHEN pm.pair_id=wa.pair_a_id THEN u.first_name||' '||u.last_name END,' / ') FILTER(WHERE pm.pair_id=wa.pair_a_id) pair_a,string_agg(DISTINCT CASE WHEN pm.pair_id=wa.pair_b_id THEN u.first_name||' '||u.last_name END,' / ') FILTER(WHERE pm.pair_id=wa.pair_b_id) pair_b FROM wheel_assignments wa JOIN leagues l ON l.id=wa.league_id JOIN categories c ON c.id=wa.category_id JOIN venues v ON v.id=wa.venue_id JOIN pair_members pm ON pm.pair_id IN(wa.pair_a_id,wa.pair_b_id) JOIN users u ON u.id=pm.user_id WHERE wa.schedule_confirmed_at IS NOT NULL AND wa.status IN('open','result_pending','disputed') GROUP BY wa.id,l.slug,c.number,v.name,v.address ORDER BY wa.scheduled_at LIMIT 100`)).rows;}
export async function ranking(){return (await pool.query(`SELECT l.slug,c.number,p.id pair_id,p.position,p.elo,p.competition_state,string_agg(u.first_name||' '||u.last_name,' / ' ORDER BY u.id) players,(SELECT count(*) FROM matches m WHERE m.pair_a_id=p.id OR m.pair_b_id=p.id) played,(SELECT count(*) FROM matches m WHERE m.winner_pair_id=p.id) wins,(SELECT COALESCE(sum(CASE WHEN m.pair_a_id=p.id THEN m.pair_a_games-m.pair_b_games ELSE m.pair_b_games-m.pair_a_games END),0) FROM matches m WHERE m.pair_a_id=p.id OR m.pair_b_id=p.id) game_diff FROM pairs p JOIN leagues l ON l.id=p.league_id JOIN categories c ON c.id=p.category_id JOIN pair_members pm ON pm.pair_id=p.id JOIN users u ON u.id=pm.user_id WHERE p.competition_state<>'inactive' GROUP BY p.id,l.slug,c.number ORDER BY l.slug,c.number,p.position`)).rows;}
export async function records(){return (await pool.query(`SELECT DISTINCT ON(l.id) l.slug,e.pair_name,e.elo,e.defenses,e.achieved_at FROM leagues l LEFT JOIN elo_record_history e ON e.league_id=l.id ORDER BY l.id,e.elo DESC NULLS LAST,e.achieved_at ASC NULLS LAST`)).rows;}
export async function recentResults(){return (await pool.query(`
  SELECT m.id,m.played_at,m.result_type,m.score,m.pair_a_id,m.pair_b_id,m.winner_pair_id,l.slug,m.category_number,
    (SELECT string_agg(u.first_name||' '||u.last_name,' / ' ORDER BY u.id) FROM pair_members pm JOIN users u ON u.id=pm.user_id WHERE pm.pair_id=m.pair_a_id) pair_a,
    (SELECT string_agg(u.first_name||' '||u.last_name,' / ' ORDER BY u.id) FROM pair_members pm JOIN users u ON u.id=pm.user_id WHERE pm.pair_id=m.pair_b_id) pair_b
  FROM matches m JOIN leagues l ON l.id=m.league_id
  ORDER BY m.played_at DESC,m.id DESC LIMIT 50
`)).rows;}
export async function pairProfile(pairId){const pair=(await pool.query(`SELECT l.slug,c.number,p.id,p.position,p.elo,p.competition_state,string_agg(u.first_name||' '||u.last_name,' / ' ORDER BY u.id) players,(SELECT count(*) FROM matches m WHERE m.pair_a_id=p.id OR m.pair_b_id=p.id) played,(SELECT count(*) FROM matches m WHERE m.winner_pair_id=p.id) wins FROM pairs p JOIN leagues l ON l.id=p.league_id JOIN categories c ON c.id=p.category_id JOIN pair_members pm ON pm.pair_id=p.id JOIN users u ON u.id=pm.user_id WHERE p.id=$1 AND p.competition_state<>'inactive' GROUP BY p.id,l.slug,c.number`,[pairId])).rows[0];if(!pair)throw problem('Pareja inexistente',404);const matches=(await pool.query(`SELECT id,pair_a_id,pair_b_id,winner_pair_id,result_type,score,played_at FROM matches WHERE (pair_a_id=$1 OR pair_b_id=$1) ORDER BY played_at DESC,id DESC LIMIT 20`,[pairId])).rows;const events=(await pool.query(`SELECT event_type,data,created_at FROM competitive_events WHERE pair_id=$1 AND event_type IN('match_confirmed','position_penalty','promotion','relegation','ladder_swap') ORDER BY created_at DESC,id DESC LIMIT 30`,[pairId])).rows;const upcoming=(await pool.query(`SELECT wa.id,wa.scheduled_at,v.name venue_name,c.number category_number,l.slug FROM wheel_assignment_participants wap JOIN wheel_assignments wa ON wa.id=wap.assignment_id JOIN venues v ON v.id=wa.venue_id JOIN categories c ON c.id=wa.category_id JOIN leagues l ON l.id=wa.league_id WHERE wap.pair_id=$1 AND wa.schedule_confirmed_at IS NOT NULL AND wa.status IN('open','result_pending','disputed')`,[pairId])).rows[0]||null;return {pair,matches,events,upcoming};}
